version: '3'
services:
  proxy:
    container_name: proxy
    depends_on:
      - soundoftext-api
      - soundoftext-web
    image: caddy:2
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /opt/caddy/data:/data
      - /opt/caddy/Caddyfile:/etc/caddy/Caddyfile
  soundoftext-api:
    container_name: soundoftext-api
    depends_on:
      - soundoftext-db
    env_file: soundoftext/api.env
    image: soundoftext/api:1.2.0
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
    restart: always
  soundoftext-db:
    container_name: soundoftext-db
    image: mongo:4.2.0
    restart: always
    volumes:
      - /opt/soundoftext/db:/data/db
  soundoftext-web:
    container_name: soundoftext-web
    image: soundoftext/web:1.5.2
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
    restart: always
